#!/usr/bin/env python3
"""Generate client adapters; --check compares in memory without touching files."""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent

def generated():
    source = json.loads((ROOT / '.claude/settings.json').read_text())
    hooks = source['hooks']
    for configs in hooks.values():
        for config in configs:
            if 'matcher' in config:
                config['matcher'] = {'Bash': 'Bash|shell|exec_command', 'Write|Edit|MultiEdit': 'Write|Edit|MultiEdit|apply_patch'}.get(config['matcher'], config['matcher'])
            for hook in config['hooks']:
                hook['command'] = hook['command'].replace('$CLAUDE_PROJECT_DIR', '${CODEX_PROJECT_DIR:-.}')
    result = {'hooks.json': json.dumps({'hooks': hooks}, indent=2) + '\n'}
    for source in sorted((ROOT / '.claude/agents').glob('*.md')):
        head, body = source.read_text().split('---', 2)[1:]
        # Agent adapter metadata deliberately supports only simple scalar fields.
        values = {}
        for line in head.strip().splitlines():
            key, sep, value = line.partition(':')
            if not sep or not value.strip() or value.strip() in {'|', '>'}:
                raise ValueError('Use one-line scalar agent metadata: ' + str(source))
            values[key.strip()] = value.strip()
        result['agents/' + source.stem + '.toml'] = ('# Generated by scripts/sync-codex.sh.\n' +
            'name = ' + json.dumps(values.get('name', source.stem), ensure_ascii=False) + '\n' +
            'description = ' + json.dumps(values['description'], ensure_ascii=False) + '\n' +
            'developer_instructions = ' + json.dumps(body.strip(), ensure_ascii=False) + '\n')
    return result

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    outputs = generated(); dest = ROOT / '.codex'
    stale = {str(p.relative_to(dest)) for p in (dest / 'agents').glob('*.toml')} - set(outputs)
    drift = [name for name, text in outputs.items() if not (dest/name).exists() or (dest/name).read_text() != text]
    if args.check:
        if drift or stale:
            print('Client adapter drift: ' + ', '.join(sorted(set(drift) | stale)))
            print('Run bash scripts/sync-codex.sh, then review the generated changes.')
            return 1
        print('Client adapters are in sync.'); return 0
    for name in stale:
        print('Stale adapter retained for review: .codex/' + name)
    for name, content in outputs.items():
        path = dest / name; path.parent.mkdir(parents=True, exist_ok=True); path.write_text(content)
    print('Generated client adapters.'); return 0

if __name__ == '__main__':
    sys.exit(main())
