#!/bin/bash
# sync-codex.sh — regenerate Codex CLI configuration from Claude Code source-of-truth
#
# What it syncs:
#   .claude/settings.json   →  .codex/hooks.json    (hook event wiring)
#   .claude/agents/*.md     →  .codex/agents/*.toml (subagent definitions)
#
# What it doesn't touch:
#   .codex/config.toml      — has Codex-specific config (MCP servers, features, profiles)
#   .codex/hooks/           — symlink to .claude/hooks/ (script content shared)
#   .agents/skills/         — read by both tools natively, no sync needed
#
# Usage: bash scripts/sync-codex.sh
# Pre-commit: scripts/verify-sync.sh runs this in dry-run and fails on drift.

set -euo pipefail

REPO_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_DIR"

# === HOOKS: .claude/settings.json → .codex/hooks.json ===
sync_hooks() {
  if [[ ! -f .claude/settings.json ]]; then
    echo "WARN: .claude/settings.json not found, skipping hook sync" >&2
    return
  fi

  # Codex hooks.json structure mirrors Claude's (PreToolUse/PostToolUse arrays of {matcher, hooks}).
  # We rewrite the command path: $CLAUDE_PROJECT_DIR → $CODEX_PROJECT_DIR.
  # Matchers translate roughly: Bash stays Bash (Codex also exposes shell as Bash), Write|Edit|MultiEdit
  # gets apply_patch appended for Codex's file-edit primitive.
  jq '
    {
      "//": "Generated by scripts/sync-codex.sh from .claude/settings.json. Do not edit by hand.",
      "//note": "Codex CLI hooks. Path uses CODEX_PROJECT_DIR. Hook scripts symlinked from .claude/hooks/.",
      hooks: (
        .hooks
        | with_entries(
            .value |= map(
              .matcher |= (
                if . == "Write|Edit|MultiEdit" then "Write|Edit|MultiEdit|apply_patch"
                elif . == "Bash" then "Bash|shell"
                else . end
              )
              | .hooks |= map(
                  .command |= (gsub("\\$CLAUDE_PROJECT_DIR"; "${CODEX_PROJECT_DIR:-.}")
                              | gsub("\"\\$CODEX_PROJECT_DIR:-\\.\\}"; "\"${CODEX_PROJECT_DIR:-.}"))
                )
            )
          )
      )
    }
  ' .claude/settings.json > .codex/hooks.json.tmp

  mv .codex/hooks.json.tmp .codex/hooks.json
  echo "  ✓ .codex/hooks.json"
}

# === AGENTS: .claude/agents/*.md → .codex/agents/*.toml ===
# Uses Ruby for proper YAML frontmatter parsing (handles block scalars, quoting, etc.)
sync_agents() {
  if ! command -v ruby >/dev/null 2>&1; then
    echo "WARN: ruby not found; skipping agent sync. Install ruby or sync manually." >&2
    return
  fi

  mkdir -p .codex/agents
  for src in .claude/agents/*.md; do
    [[ -f "$src" ]] || continue
    base=$(basename "$src" .md)
    dest=".codex/agents/${base}.toml"

    ruby -ryaml -e "
      Encoding.default_external = 'UTF-8'
      content = File.read('$src', encoding: 'UTF-8')
      parts = content.split('---', 3)
      abort('No frontmatter in $src') if parts.length < 3
      fm = YAML.safe_load(parts[1])
      body = parts[2].strip

      name = fm['name'] || '$base'
      desc = fm['description'].to_s.strip

      File.open('$dest.tmp', 'w') do |f|
        f.puts \"# Generated by scripts/sync-codex.sh from $src. Do not edit by hand.\"
        f.puts
        f.puts \"name = #{name.inspect}\"
        f.puts \"description = \\\"\\\"\\\"\"
        f.puts desc
        f.puts \"\\\"\\\"\\\"\"
        f.puts \"developer_instructions = \\\"\\\"\\\"\"
        f.puts body
        f.puts \"\\\"\\\"\\\"\"
      end
    "

    mv "$dest.tmp" "$dest"
    echo "  ✓ $dest"
  done
}

echo "Syncing Codex config from Claude Code source-of-truth..."
sync_hooks
sync_agents
echo "Done. Run 'git diff .codex/' to review."
